#!/usr/bin/env python3
"""gen-font.py — emit font8x13.h, a committed C bitmap-font header for skin-render.c.

The SDL3 renderer needs legible text (the manufacturer>device picker labels, the title) but we
will not take an SDL_ttf / SDL_image dependency on the build hosts (mm has no PIL either). So we
rasterize PIL's BUNDLED default bitmap font ONCE here on the laptop into a packed C array and
COMMIT the header — the C build is then dependency-free and reproducible on mm. Run only when the
font needs regenerating; the output font8x13.h is the source of truth checked into the repo.

    python3 gen-font.py            # writes ./font8x13.h
"""
import os
from PIL import Image, ImageDraw, ImageFont

CW, CH = 8, 13                 # cell: 8px wide (1 byte/row), 13 rows
FIRST, LAST = 32, 126          # printable ASCII

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    font = ImageFont.load_default()
    rows = []
    for cp in range(FIRST, LAST + 1):
        img = Image.new("L", (CW, CH), 0)
        d = ImageDraw.Draw(img)
        d.text((0, 0), chr(cp), fill=255, font=font)
        px = img.load()
        glyph = []
        for y in range(CH):
            bits = 0
            for x in range(CW):
                if px[x, y] > 96:
                    bits |= (1 << (7 - x))
            glyph.append(bits)
        rows.append((cp, glyph))

    with open(os.path.join(HERE, "font8x13.h"), "w") as f:
        f.write("// font8x13.h — GENERATED by gen-font.py (PIL default font). DO NOT EDIT.\n")
        f.write("// 8x13 1bpp glyphs for ASCII %d..%d; MSB = leftmost pixel.\n" % (FIRST, LAST))
        f.write("#ifndef FONT8X13_H\n#define FONT8X13_H\n")
        f.write("#define FONT_W %d\n#define FONT_H %d\n" % (CW, CH))
        f.write("#define FONT_FIRST %d\n#define FONT_LAST %d\n" % (FIRST, LAST))
        f.write("static const unsigned char FONT8X13[%d][%d] = {\n" % (LAST - FIRST + 1, CH))
        for cp, glyph in rows:
            f.write("  {" + ",".join("0x%02x" % b for b in glyph) + "}, // %d '%s'\n"
                    % (cp, chr(cp) if cp != 32 else " "))
        f.write("};\n#endif\n")
    print("wrote font8x13.h (%d glyphs, %dx%d)" % (LAST - FIRST + 1, CW, CH))


if __name__ == "__main__":
    main()
