"""evdev_codes.py — GENERATED by gen_evdev_codes.py from the kernel ABI headers.

DO NOT EDIT BY HAND. Regenerate: ``python3 synth/gen_evdev_codes.py --platform <dir>``.
Verify in CI: ``python3 synth/gen_evdev_codes.py --platform <dir> --check``.

Name -> numeric evdev code, for EXACTLY the vocabulary the capability schema validates
against (BTN/KEY/ABS/FF imported from platform core/caps.py) plus the EV_/BUS_/SYN_
transport families the synth needs. The values are kernel ABI (input-event-codes.h /
input.h), resolved through aliases (BTN_A == BTN_SOUTH == 0x130).
"""

EV = {
    'EV_SYN': 0x0,
    'EV_KEY': 0x1,
    'EV_REL': 0x2,
    'EV_ABS': 0x3,
    'EV_MSC': 0x4,
    'EV_SW': 0x5,
    'EV_LED': 0x11,
    'EV_SND': 0x12,
    'EV_REP': 0x14,
    'EV_FF': 0x15,
    'EV_PWR': 0x16,
    'EV_FF_STATUS': 0x17,
}

BUS = {
    'BUS_PCI': 0x1,
    'BUS_USB': 0x3,
    'BUS_HIL': 0x4,
    'BUS_BLUETOOTH': 0x5,
    'BUS_VIRTUAL': 0x6,
    'BUS_I2C': 0x18,
    'BUS_HOST': 0x19,
    'BUS_GSC': 0x1a,
    'BUS_ATARI': 0x1b,
    'BUS_SPI': 0x1c,
}

SYN = {
    'SYN_REPORT': 0x0,
    'SYN_CONFIG': 0x1,
    'SYN_MT_REPORT': 0x2,
    'SYN_DROPPED': 0x3,
}

BTN = {
    'BTN_TRIGGER': 0x120,
    'BTN_THUMB': 0x121,
    'BTN_A': 0x130,
    'BTN_SOUTH': 0x130,
    'BTN_B': 0x131,
    'BTN_EAST': 0x131,
    'BTN_C': 0x132,
    'BTN_NORTH': 0x133,
    'BTN_X': 0x133,
    'BTN_WEST': 0x134,
    'BTN_Y': 0x134,
    'BTN_Z': 0x135,
    'BTN_TL': 0x136,
    'BTN_TR': 0x137,
    'BTN_TL2': 0x138,
    'BTN_TR2': 0x139,
    'BTN_SELECT': 0x13a,
    'BTN_START': 0x13b,
    'BTN_MODE': 0x13c,
    'BTN_THUMBL': 0x13d,
    'BTN_THUMBR': 0x13e,
    'BTN_DPAD_UP': 0x220,
    'BTN_DPAD_DOWN': 0x221,
    'BTN_DPAD_LEFT': 0x222,
    'BTN_DPAD_RIGHT': 0x223,
}

KEY = {
    'KEY_ESC': 0x1,
    'KEY_ENTER': 0x1c,
    'KEY_HOME': 0x66,
    'KEY_VOLUMEDOWN': 0x72,
    'KEY_VOLUMEUP': 0x73,
    'KEY_POWER': 0x74,
    'KEY_MENU': 0x8b,
    'KEY_BACK': 0x9e,
    'KEY_HOMEPAGE': 0xac,
}

ABS = {
    'ABS_X': 0x0,
    'ABS_Y': 0x1,
    'ABS_Z': 0x2,
    'ABS_RX': 0x3,
    'ABS_RY': 0x4,
    'ABS_RZ': 0x5,
    'ABS_THROTTLE': 0x6,
    'ABS_RUDDER': 0x7,
    'ABS_GAS': 0x9,
    'ABS_BRAKE': 0xa,
    'ABS_HAT0X': 0x10,
    'ABS_HAT0Y': 0x11,
    'ABS_HAT1X': 0x12,
    'ABS_HAT1Y': 0x13,
}

FF = {
    'FF_RUMBLE': 0x50,
    'FF_PERIODIC': 0x51,
    'FF_CONSTANT': 0x52,
    'FF_SPRING': 0x53,
    'FF_FRICTION': 0x54,
    'FF_DAMPER': 0x55,
    'FF_INERTIA': 0x56,
    'FF_RAMP': 0x57,
}

# Merged input-code table (BTN + KEY + ABS) for descriptor code -> value lookup.
CODE = {}
for _t in (BTN, KEY, ABS):
    CODE.update(_t)


def code_value(name):
    """Numeric value for a BTN_/KEY_/ABS_ code name; KeyError if unknown."""
    return CODE[name]
