#!/usr/bin/env python3
"""gen_evdev_codes.py — derive synth/evdev_codes.py from the kernel ABI headers.

The simulator must turn descriptor strings (``BTN_SOUTH``, ``ABS_Z``, ``KEY_HOMEPAGE``)
into the numeric evdev codes the ``uinput`` ioctls require. Those numbers are stable kernel
ABI, but the ETHOS here is *own the substrate, verify don't trust*: we do NOT hand-type
them. This generator reads ``/usr/include/linux/input-event-codes.h`` (+ ``input.h`` for the
``BUS_*`` family), resolves aliases (``BTN_A`` -> ``BTN_SOUTH`` -> 0x130), and emits the
committed table for EXACTLY the vocabulary the capability schema validates against.

The vocabulary is imported from the platform's ``core/caps.py`` (``BTN_CODES``,
``KEY_CODES``, ``ABS_CODES``, ``FF_CODES``) so the synth and the validator can never drift:
if caps.py learns a new code, ``--check`` fails until evdev_codes.py is regenerated. EV_/
BUS_/SYN_ are the transport families the synth itself needs (not part of the input-code
vocab), curated below.

Usage:
  gen_evdev_codes.py --platform <dir>            # regenerate synth/evdev_codes.py (writes)
  gen_evdev_codes.py --platform <dir> --check    # assert committed file == freshly generated
"""
import argparse
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(HERE, "evdev_codes.py")

# Transport/identity families the synth needs but the input-code vocab does NOT carry.
# Curated (small, closed) rather than whitelisted from caps.py.
EV_NAMES = ["EV_SYN", "EV_KEY", "EV_REL", "EV_ABS", "EV_MSC", "EV_SW",
            "EV_LED", "EV_SND", "EV_REP", "EV_FF", "EV_PWR", "EV_FF_STATUS"]
SYN_NAMES = ["SYN_REPORT", "SYN_CONFIG", "SYN_MT_REPORT", "SYN_DROPPED"]
BUS_NAMES = ["BUS_PCI", "BUS_USB", "BUS_HIL", "BUS_BLUETOOTH", "BUS_VIRTUAL",
             "BUS_HOST", "BUS_GSC", "BUS_ATARI", "BUS_SPI", "BUS_I2C"]

HEADER_IEC = "/usr/include/linux/input-event-codes.h"
HEADER_INPUT = "/usr/include/linux/input.h"

_DEFINE = re.compile(r"^#define\s+([A-Z][A-Z0-9_]*)\s+(\S+)")


def _import_caps(platform_dir):
    caps_path = os.path.join(platform_dir, "core", "caps.py")
    if not os.path.isfile(caps_path):
        sys.exit(f"FATAL: no caps.py at {caps_path} (pass --platform <platform checkout>)")
    spec = importlib.util.spec_from_file_location("caps", caps_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _parse_header(path):
    """Return {name: raw_token} for every simple #define in a header."""
    raw = {}
    try:
        with open(path) as f:
            for line in f:
                m = _DEFINE.match(line)
                if m:
                    raw[m.group(1)] = m.group(2)
    except OSError as e:
        sys.exit(f"FATAL: cannot read {path}: {e}")
    return raw


def _resolve(name, raw, seen=None):
    """Resolve a #define to an int, following alias chains; None if not an int/alias."""
    seen = seen or set()
    if name in seen:
        return None
    seen.add(name)
    tok = raw.get(name)
    if tok is None:
        return None
    try:
        return int(tok, 0)            # 0x130 / 304 / 0o.. literal
    except ValueError:
        if re.fullmatch(r"[A-Z][A-Z0-9_]*", tok):  # alias to another macro
            return _resolve(tok, raw, seen)
        return None                   # expression like (KEY_MAX+1) — skip


def _build_table(platform_dir):
    caps = _import_caps(platform_dir)
    raw = {}
    raw.update(_parse_header(HEADER_IEC))
    raw.update(_parse_header(HEADER_INPUT))

    def collect(names, family):
        out, missing = {}, []
        for n in sorted(names):
            v = _resolve(n, raw)
            if v is None:
                missing.append(n)
            else:
                out[n] = v
        if missing:
            sys.exit(f"FATAL: {family}: names not found/resolved in kernel headers: "
                     f"{', '.join(missing)} (header drift or a typo in the schema vocab)")
        return out

    return {
        "EV": collect(EV_NAMES, "EV_*"),
        "BUS": collect(BUS_NAMES, "BUS_*"),
        "SYN": collect(SYN_NAMES, "SYN_*"),
        "BTN": collect(caps.BTN_CODES, "BTN_* (caps.BTN_CODES)"),
        "KEY": collect(caps.KEY_CODES, "KEY_* (caps.KEY_CODES)"),
        "ABS": collect(caps.ABS_CODES, "ABS_* (caps.ABS_CODES)"),
        "FF": collect(caps.FF_CODES, "FF_* (caps.FF_CODES)"),
    }


def _emit(tables):
    def block(name, d):
        lines = [f"{name} = {{"]
        for k in sorted(d, key=lambda k: (d[k], k)):
            lines.append(f"    {k!r}: {d[k]:#x},")
        lines.append("}")
        return "\n".join(lines)

    body = "\n\n".join(block(n, tables[n]) for n in ("EV", "BUS", "SYN", "BTN", "KEY", "ABS", "FF"))
    return f'''"""evdev_codes.py — GENERATED by gen_evdev_codes.py from the kernel ABI headers.

DO NOT EDIT BY HAND. Regenerate: ``python3 synth/gen_evdev_codes.py --platform <dir>``.
Verify in CI: ``python3 synth/gen_evdev_codes.py --platform <dir> --check``.

Name -> numeric evdev code, for EXACTLY the vocabulary the capability schema validates
against (BTN/KEY/ABS/FF imported from platform core/caps.py) plus the EV_/BUS_/SYN_
transport families the synth needs. The values are kernel ABI (input-event-codes.h /
input.h), resolved through aliases (BTN_A == BTN_SOUTH == 0x130).
"""

{body}

# Merged input-code table (BTN + KEY + ABS) for descriptor code -> value lookup.
CODE = {{}}
for _t in (BTN, KEY, ABS):
    CODE.update(_t)


def code_value(name):
    """Numeric value for a BTN_/KEY_/ABS_ code name; KeyError if unknown."""
    return CODE[name]
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--platform", required=True, help="platform checkout (for core/caps.py vocab)")
    ap.add_argument("--check", action="store_true", help="assert committed file matches; non-zero on drift")
    a = ap.parse_args()

    generated = _emit(_build_table(a.platform))

    if a.check:
        if not os.path.isfile(OUT_PATH):
            sys.exit(f"FAIL: {OUT_PATH} missing — run without --check to generate it")
        with open(OUT_PATH) as f:
            current = f.read()
        if current != generated:
            sys.exit(f"FAIL: {OUT_PATH} is STALE vs the kernel headers + caps.py vocab.\n"
                     f"      Regenerate: python3 {os.path.relpath(__file__)} --platform {a.platform}")
        print(f"OK    evdev_codes.py matches the kernel ABI headers + caps.py vocab")
        return 0

    with open(OUT_PATH, "w") as f:
        f.write(generated)
    print(f"wrote {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
